"""make lead phone nullable, email required

Revision ID: 34a0dadd7dff
Revises: 2a21e38da594
Create Date: 2026-05-19 11:15:21.881871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a0dadd7dff'
down_revision: Union[str, None] = '2a21e38da594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
