"""add_users_cache_and_processed_events

Revision ID: 2ac6ec72a60e
Revises: deeac686ca26
Create Date: 2026-05-01 20:03:22.374917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ac6ec72a60e'
down_revision = 'deeac686ca26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_processed_events_event_type'), 'processed_events', ['event_type'], unique=False)
    op.create_table('users_cache',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='occurred_at последнего применённого события'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False, comment='Когда запись впервые попала в локальный кеш'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cache_email'), 'users_cache', ['email'], unique=False)
    op.create_index('ix_users_cache_role_active', 'users_cache', ['role_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_cache_role_id'), 'users_cache', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_cache_role_name'), 'users_cache', ['role_name'], unique=False)
    op.create_index(op.f('ix_users_cache_studio_id'), 'users_cache', ['studio_id'], unique=False)
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('studio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('login_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('privacy_policy_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('privacy_policy_accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    op.drop_index(op.f('ix_users_cache_studio_id'), table_name='users_cache')
    op.drop_index(op.f('ix_users_cache_role_name'), table_name='users_cache')
    op.drop_index(op.f('ix_users_cache_role_id'), table_name='users_cache')
    op.drop_index('ix_users_cache_role_active', table_name='users_cache')
    op.drop_index(op.f('ix_users_cache_email'), table_name='users_cache')
    op.drop_table('users_cache')
    op.drop_index(op.f('ix_processed_events_event_type'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
