"""Create studios and classrooms tables

Revision ID: deeac686ca26
Revises: 
Create Date: 2025-12-10 01:33:02.298825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deeac686ca26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название студии'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание студии'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='Адрес студии'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Телефон студии'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email студии'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли студия'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studios_is_active'), 'studios', ['is_active'], unique=False)
    op.create_index(op.f('ix_studios_name'), 'studios', ['name'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False, comment='ID студии'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название кабинета'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='Вместимость кабинета (количество человек)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание кабинета'),
    sa.Column('equipment', sa.Text(), nullable=True, comment='Оборудование в кабинете (микрофоны, пианино и т.д.)'),
    sa.Column('floor', sa.Integer(), nullable=True, comment='Этаж'),
    sa.Column('room_number', sa.String(length=20), nullable=True, comment='Номер кабинета'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли кабинет'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_is_active'), 'classrooms', ['is_active'], unique=False)
    op.create_index(op.f('ix_classrooms_studio_id'), 'classrooms', ['studio_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_classrooms_studio_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_is_active'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_studios_name'), table_name='studios')
    op.drop_index(op.f('ix_studios_is_active'), table_name='studios')
    op.drop_table('studios')
    op.drop_table('roles', schema='public')
    # ### end Alembic commands ###
