"""Fix model relationships

Revision ID: 16d9060f63a7
Revises: c44e4d5edb87
Create Date: 2025-08-29 23:11:26.001340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d9060f63a7'
down_revision = 'c44e4d5edb87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###