"""initial schema

Revision ID: 4faa0ba51e82
Revises: 
Create Date: 2026-05-31 17:48:33.903868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4faa0ba51e82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_states',
    sa.Column('vk_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('outbound_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_event_type', sa.String(length=128), nullable=True),
    sa.Column('source_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_status'), 'outbound_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_messages_vk_id'), 'outbound_messages', ['vk_id'], unique=False)
    op.create_index('ix_outbound_status_id', 'outbound_messages', ['status', 'id'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('user_tokens',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_tokens_vk_id'), 'user_tokens', ['vk_id'], unique=False)
    op.create_table('users_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cache_vk_id'), 'users_cache', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cache_vk_id'), table_name='users_cache')
    op.drop_table('users_cache')
    op.drop_index(op.f('ix_user_tokens_vk_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_table('processed_events')
    op.drop_index('ix_outbound_status_id', table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_vk_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_status'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_table('dialog_states')
    # ### end Alembic commands ###
