"""
Pydantic схемы для Profile Service
"""

# Схемы профилей
from app.schemas.profile import (
    ProfileBase,
    ProfileCreate,
    ProfileUpdate,
    NotificationPreferences,
    ProfileSettings,
    UserInfo,
    ProfileResponse,
    ProfilePublicResponse,
    ProfileSearchResult,
    ProfileListResponse,
    AvatarUploadResponse,
    AvatarInfo,
    StudentInfo,
    TeacherInfo,
    ProfileStatsResponse,
    MessageResponse,
    ErrorResponse
)

# Общие схемы
from app.schemas.common import (
    SuccessResponse,
    ErrorResponse as CommonErrorResponse,
    PaginationParams,
    PaginationInfo,
    PaginatedResponse,
    HealthCheckResponse,
    ServiceStatsResponse,
    CacheStatsResponse,
    ValidationError,
    ValidationErrorResponse,
    SearchParams,
    TimeRangeParams,
    FilterParams,
    BulkOperationRequest,
    BulkOperationResponse,
    FileUploadResponse,
    UserActivitySummary,
    ServiceInfo,
    MetricsResponse,
    ConfigurationResponse,
    BackupInfo,
    SystemMaintenanceInfo
)

__all__ = [
    # Profile schemas
    "ProfileBase",
    "ProfileCreate", 
    "ProfileUpdate",
    "NotificationPreferences",
    "ProfileSettings",
    "UserInfo",
    "ProfileResponse",
    "ProfilePublicResponse",
    "ProfileSearchResult",
    "ProfileListResponse",
    "AvatarUploadResponse",
    "AvatarInfo",
    "StudentInfo",
    "TeacherInfo",
    "ProfileStatsResponse",
    "MessageResponse",
    
    # Comment schemas
    "CommentBase",
    "CommentCreate",
    "CommentUpdate", 
    "AuthorInfo",
    "CommentResponse",
    "CommentListResponse",
    "ReviewCreate",
    "ReviewResponse",
    "RatingStats",
    "TeacherReviewsResponse",
    "AdminNoteCreate",
    "CommentModerationRequest",
    "LessonCommentCreate",
    "CommentStatsResponse",
    "RecentCommentsResponse",
    "CommentTargetInfo",
    "UserCommentsResponse",
    
    # Dashboard schemas
    "ActivityItem",
    "LessonInfo",
    "UpcomingLessons",
    "LessonHistory",
    "AvailableTeachers",
    "StudentStats",
    "TeachingStats",
    "TodaySchedule",
    "ReviewsSummary",
    "MyComments",
    "QuickAction",
    "SystemStats",
    "TopTeacher",
    "AdminNoteItem",
    "StudentDashboard",
    "TeacherDashboard",
    "AdminDashboard",
    "DefaultDashboard",
    "DashboardResponse",
    "DashboardError",
    
    # Common schemas
    "SuccessResponse",
    "CommonErrorResponse",
    "PaginationParams",
    "PaginationInfo", 
    "PaginatedResponse",
    "HealthCheckResponse",
    "ServiceStatsResponse",
    "CacheStatsResponse",
    "ValidationError",
    "ValidationErrorResponse",
    "SearchParams",
    "TimeRangeParams",
    "FilterParams",
    "BulkOperationRequest",
    "BulkOperationResponse",
    "FileUploadResponse",
    "UserActivitySummary",
    "ServiceInfo",
    "MetricsResponse",
    "ConfigurationResponse",
    "BackupInfo",
    "SystemMaintenanceInfo"
]