"""initial profile schema

Revision ID: f85a421d33b7
Revises: 
Create Date: 2026-07-19 13:09:49.237114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85a421d33b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_processed_events_event_type'), 'processed_events', ['event_type'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя из Auth Service'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='Отображаемое имя пользователя'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Биография пользователя'),
    sa.Column('avatar_filename', sa.String(length=255), nullable=True, comment='Имя файла аватара'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Номер телефона'),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True, comment='Дата рождения'),
    sa.Column('is_profile_public', sa.Boolean(), nullable=False, comment='Публичность профиля'),
    sa.Column('show_contact_info', sa.Boolean(), nullable=False, comment='Показывать контактную информацию'),
    sa.Column('notification_preferences', sa.JSON(), nullable=False, comment='Настройки уведомлений в JSON формате'),
    sa.Column('profile_settings', sa.JSON(), nullable=False, comment='Настройки профиля в JSON формате'),
    sa.Column('profile_views', sa.Integer(), nullable=False, comment='Количество просмотров профиля'),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True, comment='Время последней активности'),
    sa.Column('student_info', sa.JSON(), nullable=True, comment='Дополнительная информация о студенте'),
    sa.Column('teacher_info', sa.JSON(), nullable=True, comment='Дополнительная информация о преподавателе'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('users_cache',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='occurred_at последнего применённого события'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False, comment='Когда запись впервые попала в локальный кеш'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cache_email'), 'users_cache', ['email'], unique=False)
    op.create_index('ix_users_cache_role_active', 'users_cache', ['role_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_cache_role_id'), 'users_cache', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_cache_role_name'), 'users_cache', ['role_name'], unique=False)
    op.create_index(op.f('ix_users_cache_studio_id'), 'users_cache', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cache_studio_id'), table_name='users_cache')
    op.drop_index(op.f('ix_users_cache_role_name'), table_name='users_cache')
    op.drop_index(op.f('ix_users_cache_role_id'), table_name='users_cache')
    op.drop_index('ix_users_cache_role_active', table_name='users_cache')
    op.drop_index(op.f('ix_users_cache_email'), table_name='users_cache')
    op.drop_table('users_cache')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_processed_events_event_type'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###